NAMEDCHIP_UNIQUE_CROSSFIRE_1 = 0
NAMEDCHIP_RARE_CROSSFIRE_1 = 1
NAMEDCHIP_RARE_CROSSFIRE_2 = 2
NAMEDCHIP_UNIQUE_CROSSFIRE_2 = 3

//--[[
$NAMEDCHIP_UNIQUE_CROSSFIRE_1 = 0;
$NAMEDCHIP_RARE_CROSSFIRE_1 = 1;
$NAMEDCHIP_RARE_CROSSFIRE_2 = 2;
$NAMEDCHIP_UNIQUE_CROSSFIRE_2 = 3;
//]]
