//-- Shared between game server and item server.
//-- Messing with this list will probably cause undesired effects.
//-- Coded crappily so its easily ported to different languages.

ENHANCEMENT_TYPE_WEAPON = 0
ENHANCEMENT_TYPE_PLAYER = 1
ENHANCEMENT_TYPE_DEFAULT = ENHANCEMENT_TYPE_WEAPON
ENHANCEMENT_TYPE_SKILL = 2

ENHANCEMENT_MUTATOR_NONE = 0
ENHANCEMENT_MUTATOR_MULTIPLY = 1
ENHANCEMENT_MUTATOR_MULTIPLY_PERCENTAGE = 2
ENHANCEMENT_MUTATOR_ADD = 3
ENHANCEMENT_MUTATOR_SUBTRACT = 4
ENHANCEMENT_MUTATOR_DIVIDE = 5
ENHANCEMENT_MUTATOR_SQUARE = 6

//-- These are functions for more complicated chips.
ENHANCEMENT_MUTATOR_FUNCTION_NONE = 10 //-- Empty function. Nothing should be using this.

ENHANCEMENT_BULLET_DAMAGE = 0
ENHANCEMENT_BULLET_SPEED = 1

ENHANCEMENT_NAMES = {}
ENHANCEMENT_NAMES[ENHANCEMENT_BULLET_DAMAGE] = "Bullet Damage"
ENHANCEMENT_NAMES[ENHANCEMENT_BULLET_SPEED] = "Bullet Speed"

//--[[
$ENHANCEMENT_TYPE_WEAPON = 0;
$ENHANCEMENT_TYPE_PLAYER = 1;
$ENHANCEMENT_TYPE_DEFAULT = $ENHANCEMENT_TYPE_WEAPON;
$ENHANCEMENT_TYPE_SKILL = 2;

$ENHANCEMENT_MUTATOR_NONE = 0;
$ENHANCEMENT_MUTATOR_MULTIPLY = 1;
$ENHANCEMENT_MUTATOR_MULTIPLY_PERCENTAGE = 2;
$ENHANCEMENT_MUTATOR_ADD = 3;
$ENHANCEMENT_MUTATOR_SUBTRACT = 4;
$ENHANCEMENT_MUTATOR_DIVIDE = 5;
$ENHANCEMENT_MUTATOR_SQUARE = 6;

//-- These are functions for more complicated chips.
$ENHANCEMENT_MUTATOR_FUNCTION_NONE = 10; //-- Empty function. Nothing should be using this.

$ENHANCEMENT_BULLET_DAMAGE = 0;
$ENHANCEMENT_BULLET_SPEED = 1;

$ENHANCEMENT_NAMES = array();
$ENHANCEMENT_NAMES[$ENHANCEMENT_BULLET_DAMAGE] = "Bullet Damage";
$ENHANCEMENT_NAMES[$ENHANCEMENT_BULLET_SPEED] = "Bullet Speed";
//]]
